### ISSUE TITLE
Compatible with MySQL?

### ISSUE THREAD

**Issue by mattbue** [marcusolsson/grafana-gantt-panel#1]
Hi, is this plugin compatible with MySQL/MariaDB?

**Comment by marcusolsson** [comment]
I haven't tried it myself, but it works with the PostgreSQL data source, so I'm pretty sure it works with MySQL as well. Let me know if it doesn't and I'll fix it. 

You SQL query needs to return:

- A text column (two if you want to group the results)
- Two time columns (start time, end time)

It's important that you set it to return a Table instead of Time series.

Let me know how it goes!

**Comment by mattbue** [comment]
Tried it using the following database table 't_gantt_test':
![image](https://user-images.githubusercontent.com/7815776/104458433-aa4eed80-55ab-11eb-9763-916b3c78890e.png)

Table content:
![image](https://user-images.githubusercontent.com/7815776/104458490-c0f54480-55ab-11eb-9d6b-a9216a987249.png)

My query looks like this:
```
SELECT
  UNIX_TIMESTAMP(Start) AS "time",
  UNIX_TIMESTAMP(Ende) AS "time2",
  Name
FROM t_gantt_test
```

The query result looks like this:
![image](https://user-images.githubusercontent.com/7815776/104458735-06197680-55ac-11eb-8d2a-7e8f0e657ed2.png)

The chart looks like this:
![image](https://user-images.githubusercontent.com/7815776/104459002-6d372b00-55ac-11eb-8a4e-b77c83617c75.png)

The "bars" are only a line on the start time. Not from start to end time.
I'm wondering why the number of digits of unix start and end time are different...

**Comment by marcusolsson** [comment]
I _think_ it's because `time` is a special keyword for the MySQL data source. If the SQL result contains a column called `time`, it's treated differently. Judging by your screenshot, it looks like Grafana converts it to milliseconds. 

Maybe try something like:

```
SELECT
  UNIX_TIMESTAMP(Start) * 1000 as "start",
  UNIX_TIMESTAMP(Ende) * 1000 as "end",
  Name
FROM t_gantt_test
```

**Comment by mattbue** [comment]
Using the following query
```
SELECT
  UNIX_TIMESTAMP(Start) * 1000 as "start",
  UNIX_TIMESTAMP(Ende) * 1000 as "end",
  Name
FROM t_gantt_test
```
gives a plausible data table
![image](https://user-images.githubusercontent.com/7815776/104552481-365b2680-5639-11eb-887f-d7a1eaa94a07.png)

But i cannot select the two time columns for start time and end time.
![image](https://user-images.githubusercontent.com/7815776/104552601-6c000f80-5639-11eb-9130-dd660256fb25.png)

**Comment by marcusolsson** [comment]
Hm. Looks like the data source returns the timestamps as number fields rather than time fields. I'm looking at the documentation for table queries, and it looks like you can return the date column as is without converting to UNIX_TIMESTAMP.

https://grafana.com/docs/grafana/latest/datasources/mysql/#table-queries

If that doesn't do it for you, I'll be able to troubleshoot this weekend. If the MySQL data source doesn't supported time fields yet (it's one of the oldest data sources), I'll add an option to convert from number fields.

Thanks for trying this out!

**Comment by mattbue** [comment]
Using
```
SELECT
  Start as "start",
  Ende as "end",
  Name as "my_name"
FROM t_gantt_test
```
I still cannot choose the time colums.

**Comment by marcusolsson** [comment]
Thank you for letting me know! 🙏 I'll dig into this during the weekend and get back to you.

**Comment by marcusolsson** [comment]
Indeed the MySQL data source only seems to be able to handle _one_ time field at the most. I'm thinking we could let users select strings and number fields for start and end time and then convert them to time fields in the plugin. I'll try to get to this in the next couple of days.

**Comment by mattbue** [comment]
Ok.
Let me know if you have something i shall test.

**Comment by vaughanbrittonsage** [comment]
@marcusolsson I seem to be having a similar issue with using an Elasticsearch datasource. It would be great if we could select any field and have it attempt to convert it within the plugin.

**Comment by marcusolsson** [comment]
I've published v0.2.0 which allows you to use string and number fields as time. Hopefully that will solve your issue, otherwise let me know!

**Comment by vaughanbrittonsage** [comment]
Brilliant, thanks I'll take a look

**Comment by mattbue** [comment]
Thanks for your work. Tomorrow i will test it and let you know.
