### ISSUE TITLE
Cant install the plugin

### ISSUE THREAD

**Issue by mbarradas** [marcusolsson/grafana-gantt-panel#3]
I get this message while trying to install on a docker image

![Plugin](https://user-images.githubusercontent.com/67159947/106020203-1d1a9700-6089-11eb-8f41-f18fbd4ffc01.PNG)

Grafana version 7.0.3

**Comment by marcusolsson** [comment]
The error you're getting is most likely because there are no _supported_ versions of the plugin for the Grafana version you're running. grafana-cli checks whether your currently installed version of Grafana satisfies the `grafanaDependency` of the plugin. 

The minimum supported version for the plugin is 7.3. I'll likely be requiring 7.3 for most of my plugins going forward, as that's when the new forms styles where introduced, and I don't want to maintain two separate form components. Depending on the demand, we could look into building an abstraction layer for form components that checks the current version and falls back to the legacy form components for earlier versions.

**Comment by mbarradas** [comment]
No problem I guess we would only need to state that on the info of the panel. 
I'm testing on that older version because its already available on the docker environment I'm working with. 
Thanks! and as always good work!

**Comment by marcusolsson** [comment]
> on the info of the panel

What "info" are you referring to here? I'd like to see a slightly better error message from grafana-cli, along the lines of:

> Failed to install plugin: No supported versions available for your Grafana version

If you install an unsupported plugin without using grafana-cli, you get a cryptic "Minified React error" when you try to use it. Grafana should be able to give you better information here.

**Comment by mbarradas** [comment]
On the plugin details page
https://grafana.com/grafana/plugins/marcusolsson-gantt-panel/installation
The note says you need Grafana 3.0 or greater I guess it needs to say 7.3 or Greater and I agree on grafana-cli comment

![descarga (3)](https://user-images.githubusercontent.com/67159947/106042458-b2765500-60a2-11eb-8527-eba053f2391d.png)

**Comment by marcusolsson** [comment]
Unfortunately, that's a generic instructions displayed for all plugins, and not something the plugin author controls. I agree it is a bit confusing though. I'll let the team know! Thanks!
