### ISSUE TITLE
Plugin panel does not load in anonymous mode - Grafana 8.1

### ISSUE THREAD

**Issue by jkbiersepp** [marcusolsson/grafana-gantt-panel#50]
@marcusolsson: 
Hello, I am a big fan of this panel and all your recent development into the panel. Thank you for this!

However I noticed an issue which is rather weird. In the authentifaction free area of grafana (anonymous mode) the plugin does not load. When you login as a user then the panel works just fine.  I have your experimental features running: Lock to extend. 

Here my currently used specs: 
- Windows Server 2019
- Grafana 8.1.1
- Data_Source: MSSQL-Server

What is it supposed to do: 

Load the panel.

What is it currently doing: 

Error loading: marcusolsson-gantt-panel

This plugin requires a more recent version of Grafana (>=7.3.0).

![image](https://user-images.githubusercontent.com/89379338/130408530-0806a6f3-3634-4ef5-adcd-5b91d8dea27d.png)

**Comment by marcusolsson** [comment]
Hi,

The issue is likely not that that you have anonymous mode enabled, but that you're hiding the Grafana version. To stay backwards-compatible, the plugin checks the currently running version of Grafana to determine what features is has access to. When you hide the version, the plugin no longer knows what functionality it can safely depend on.

You can solve it by not hiding the version, but if you're intentionally hiding it, unfortunately there's not much you can do at this point.

**Comment by jkbiersepp** [comment]
Perfect. Thanks this solves the issue. I didn't know that there was this option in the custom.ini 

Now it runs on both modes.
