### ISSUE TITLE
Dimension for colering activities

### ISSUE THREAD

**Issue by Andi1986** [marcusolsson/grafana-gantt-panel#8]
Currently activities are all shown with green corlor.
for visualizing certain states of activities it would be nice to have **an optional** seperate dimension declaring the color.
The field type for this dimension should probably be a typical hex value representing a color.

See example use case here: #7

**Comment by marcusolsson** [comment]
I like this idea! Makes total sense to use color to add another dimension to the chart. I think the main challenge here is the UX of how you'd configure the color. I'm dumping some thoughts here:

- I would like to use the Grafana color picker for this rather than having users come up with good colors. My guess is that most users just want different colors, but don't care that much about the actual hex code.
- I think it would make sense to be able to select a "Color by" field. One idea is to make it behave differently based on the type of the field:
  - If the field is of type Number, we can use the Color scheme field option to let users set colors by thresholds, for example whether an activity went over budget. This would integrate natively into Grafana's own color system, and would allow gradients even.
  - If the field is of type String, each row could be a category, such as "queued", "running", "completed". We could have a legend like the one for the Graph panel, where each unique category would get assigned a color by default. You could then override it by clicking on the color in the legend.

![prototype](https://user-images.githubusercontent.com/8396880/106800106-59895c80-6660-11eb-803f-8a941802a5a2.png)

Another approach is to have user assign the colors in the panel editor. Each unique category would be displayed in a list with a color next to it.

**Comment by Andi1986** [comment]
you are right, i guess grafana tends to use configurable thresholds rather than actual hex values. I think i would be fine with any kind of solution here as long as its possible to map categories or numbers to colors in some way

**Comment by Xasin** [comment]
Ah, it seems like people have already discovered the need for this setting, good! 
I'd just like to say that I would look forward to this as well, and might be available for a bit of testing.

This Gantt-Chart would also serve as a nice status indicator for my upcoming smart home project, with each node having a row in the Gantt chart to represent its state. A heatmap doesn't work well for things like showing how long the updating process or restart took.

Colouring the individual cells would be great for that purpose!
I am all for the "color by" cell, that would suit my purpose just fine.

**Comment by Andi1986** [comment]
Hey @marcusolsson, im just curious about the current process for this issue since it has been a whil. Are there bigger dependencies/complexities for this one ?

**Comment by marcusolsson** [comment]
I think this is ready to be worked on. Mostly I haven't had the chance to start working on it yet. I keep a [project board](https://github.com/users/marcusolsson/projects/1) where I track bugs and feature requests across all my plugins. I try to prioritize based on reactions and general demand. I've bumped the priority of this issue, and hope that I can start working on this soon.

**Comment by marcusolsson** [comment]
Got some work done on this tonight. Posted a demo in the [pull request](https://github.com/marcusolsson/grafana-gantt-panel/pull/26). Let me know what you think!

**Comment by Marius9610** [comment]
hi @marcusolsson , I would like to request the question from mvalois as a new feature. I have a similar use case where I want to show an user what state the dimension parameter is in. Thank you for your feedback.
